# Generated by Django 5.1.2 on 2025-03-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applicationform_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='application_id',
        ),
    ]
