# Generated by Django 5.1.2 on 2025-03-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
